### PR TITLE
Added the command line option for a compact output of print-values

### PR DESCRIPTION
**Pull request by mgraupner**
Most of the times I only need the important values of the inverter, so instead of fetching all of them, this adds a compact option to only fetch the ones regarding power generation.

### CODE REVIEW

**Comment by jedie** [comment]
Nice idea. But i think we can fix that in a other way: You match `--compact` with `group_name =='solar'`
Why not add all group names as a optional command argument?

**Comment by jedie** [comment]
> You mean like print-values --group 'solar'?

Yes, something like that ;)

**Comment by mgraupner** [comment]
I think the "discoverability"/UX of this would be harder than just offering the `compact` option. You would have to know the name of the groups in order to select a specific one.

**Comment by jedie** [comment]
Thanks for contribution.

**Pull request merged**
